version: '3.0'
services:
  esdiscogs:
    container_name: elasticsearch
    build: docker/elasticsearch/
    volumes:
    - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    - 'esdat1:/usr/share/elasticsearch/data'
    ports:
    - '9200:9200'
  kibana:
    build: docker/kibana/
    volumes:
    - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
    - '5601:5601'
volumes:
  esdat1:
